#!/bin/bash
set -euo pipefail

RESET='\033[0m'
BOLD='\033[1m'
CYAN='\033[36m'
MAGENTA='\033[35m'

main() {
  print_step "Check linting"
  composer run-script lint-check
  print_done

  print_step "Run test suite"
  composer run-script test
  print_done

  print_step "Git push"
}

print_step() {
  local -r description="$1"
  echo -e "${MAGENTA}${BOLD}### ${description} ###${RESET}"
}

print_done() {
  echo -e "${CYAN}Done.${RESET}"
  echo
}

main
